language: objective-c
osx_image: xcode8.2

install:
  - npm install -g cordova
  - cordova create testing com.tester.test Tester
  - cd testing
  - cordova platform add ios

script:
  - cordova plugin add https://github.com/DavidBriglio/cordova-ios10-simple-notification
  - cordova build ios
